//! Kickstarter errors
use {pledge, project};
use rustorm::database;
use std::{error, fmt, io, result};

/// A type for results generated by Kickstarter-related functions, where the Err type is kickstarter::Error.
pub type Result<T> = result::Result<T, Error>;

/// The error type for Kickstarter operations.
#[derive(Debug)]
pub enum Error {
    /// A pledge operation could not be completed.
    InvalidPledge(pledge::Error),
    /// A project operation could not be completed.
    InvalidProject(project::Error),
    /// An error occurred with the provided configuration.
    Config(String),
    /// A database operation could not be completed.
    Database(database::DbError),
    /// An I/O operation could not be completed.
    IO(io::Error),
}

impl From<pledge::Error> for Error {
    fn from(err: pledge::Error) -> Error {
        Error::InvalidPledge(err)
    }
}

impl From<project::Error> for Error {
    fn from(err: project::Error) -> Error {
        Error::InvalidProject(err)
    }
}

impl From<database::DbError> for Error {
    fn from(err: database::DbError) -> Error {
        Error::Database(err)
    }
}

impl From<io::Error> for Error {
    fn from(err: io::Error) -> Error {
        Error::IO(err)
    }
}

impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            Error::InvalidPledge(ref inner) => inner.fmt(fmt),            
            Error::InvalidProject(ref inner) => inner.fmt(fmt),
            Error::Database(ref inner) => inner.fmt(fmt),
            Error::IO(ref inner) => inner.fmt(fmt),
            Error::Config(ref inner) => inner.fmt(fmt),
        }
    }
}

impl error::Error for Error {
    fn description(&self) -> &str {
        match *self {
            Error::InvalidPledge(ref inner) => inner.description(),
            Error::InvalidProject(ref inner) => inner.description(),
            Error::Database(ref inner) => inner.description(),
            Error::IO(ref inner) => inner.description(),
            Error::Config(ref inner) => inner,
        }
    }

    fn cause(&self) -> Option<&error::Error> {
        match *self {
            Error::InvalidPledge(ref inner) => Some(inner),
            Error::InvalidProject(ref inner) => Some(inner),
            Error::Database(ref inner) => Some(inner),
            Error::IO(ref inner) => Some(inner),
            Error::Config(_) => None,
        }
    }
}
